an li shekel bakisim ain li gam prota

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -183,6 +183,20 @@ jobs:
               "annotations": {"meta.helm.sh/release-name": "flasksql-chart", "meta.helm.sh/release-namespace": "default"}
             }
           }' || echo "Service 'gif-db' not found, skipping patch."
+      
+      - name: Install Prometheus Operator CRDs
+        run: |
+          echo "Installing Prometheus Operator CRDs..."
+          kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/bundle.yaml
+          
+      - name: Verify CRDs Are Installed
+        run: |
+          echo "Verifying that Prometheus Operator CRDs exist..."
+          kubectl get crds | grep servicemonitor || echo "❌ ServiceMonitor CRD missing!"
+
+      
+      
+      
       - name: Deploy Flask App Using Helm, Updating Release
         run: |
           echo "🚀 Deploying Helm Chart to GKE"
