weird helm ti na an na na na ni

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -1,4 +1,4 @@
-name: Terraform GKE Cluster Setup and Deploy via helm
+name: Terraform GKE Cluster Setup and Deploy via Helm
 
 on:
   push:
@@ -30,20 +30,18 @@ jobs:
         run: |
           echo "IMAGE_NAME=yuvalbenar/terraflaskqlk8s" >> $GITHUB_ENV
           echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
+          echo "VERSION=0.0.${{ github.run_number }}" >> $GITHUB_ENV  # Ensure correct versioning
 
-      - name: Build Docker Image
+      - name: Build and Push Docker Image
         run: |
           docker build -t $IMAGE_NAME:$IMAGE_TAG .
           docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
-
-      - name: Push Docker Image
-        run: |
           docker push $IMAGE_NAME:$IMAGE_TAG
           docker push $IMAGE_NAME:latest
 
   terraform:
-    runs-on: ubuntu-latest
     needs: build
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -76,8 +74,8 @@ jobs:
           TF_VAR_credentials_path: "/tmp/gcp_credentials.json"
 
   deploy:
-    runs-on: ubuntu-latest
     needs: terraform
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -91,119 +89,25 @@ jobs:
           universe: googleapis.com
           cleanup_credentials: true
 
-      - name: Install Google Cloud SDK
+      - name: Install Google Cloud SDK and Helm
         run: |
           echo "Installing Google Cloud SDK"
           curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /etc/apt/trusted.gpg.d/google.asc
           echo "deb [signed-by=/etc/apt/trusted.gpg.d/google.asc] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
           sudo apt-get update
           sudo apt-get install google-cloud-sdk
-
-      - name: Install Helm
-        run: |
           echo "Installing Helm"
           curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
           helm version
 
-      - name: Add and Update Helm Repository
+      - name: Deploy Flask App Using Helm
         run: |
-          echo "Adding Helm repository"
-          helm repo add helmcharts https://yuvalbenar.github.io/helm-charts/
-          helm repo update
-          helm search repo helmcharts --versions
-
-      - name: Install GKE Google Plugin
-        run: |
-          echo "Installing GKE google plugin"
-          sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin
-
-      - name: List GKE Clusters
-        run: |
-          echo "Listing GKE clusters"
-          gcloud container clusters list --project terraflaskqlk8s
-
-      - name: Set GKE Context to Connect to Cluster
-        run: |
-          echo "Setting GKE context"
-          gcloud container clusters get-credentials flasksql-cluster --project terraflaskqlk8s --zone us-east1-b
-
-      - name: Create k8secret.yaml from GitHub Secrets
-        run: |
-          echo "Creating k8secret.yaml"
-          cat <<EOF > k8secret.yaml
-          apiVersion: v1
-          kind: Secret
-          metadata:
-            name: mysql-secrets
-          type: Opaque
-          data:
-            root_password: $(echo -n '${{ secrets.MYSQL_ROOT_PASSWORD }}' | base64)
-            database_name: $(echo -n '${{ secrets.DATABASE_NAME }}' | base64)
-            user: $(echo -n '${{ secrets.MYSQL_USER }}' | base64)
-            password: $(echo -n '${{ secrets.MYSQL_PASSWORD }}' | base64)
-          EOF
-          echo "Applying k8secret.yaml to the cluster"
-          kubectl apply -f k8secret.yaml -n default
-
-      - name: Read Version from Remote version.txt
-        id: get_version
-        run: |
-          echo "Reading version from remote version.txt"
-          VERSION=$(curl -s https://raw.githubusercontent.com/yuvalbenar/terraflaskqlk8s/k8sdeploy/version.txt)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-          echo "Using version: $VERSION"
-
-      - name: Wait for Helm Chart Update
-        run: |
-          echo "⏳ Waiting for updated Helm chart for version $VERSION..."
-          for i in {1..10}; do
-            echo "🔍 Checking for version: $VERSION"
-            curl -s https://yuvalbenar.github.io/helm-charts/index.yaml | tee helm-index.yaml
-            if grep "$VERSION" helm-index.yaml; then
-              echo "✅ Helm chart version $VERSION found. Proceeding with deployment."
-              exit 0
-            fi
-            echo "⏳ Helm chart update not found, retrying in 30 seconds..."
-            sleep 30
-          done
-          echo "❌ Error: Helm chart update not found after multiple retries. Exiting."
-          exit 1
-
-      - name: Patch Existing ConfigMaps for Helm Adoption
-        run: |
-          echo "Patching existing ConfigMap 'flask-config' to include Helm ownership metadata"
-          kubectl patch configmap flask-config -n default --type merge -p '{
-            "metadata": {
-              "labels": {"app.kubernetes.io/managed-by": "Helm"},
-              "annotations": {"meta.helm.sh/release-name": "flasksql-chart", "meta.helm.sh/release-namespace": "default"}
-            }
-          }' || echo "ConfigMap 'flask-config' not found, skipping patch."
-          echo "Patching existing ConfigMap 'mysql-config' to include Helm ownership metadata"
-          kubectl patch configmap mysql-config -n default --type merge -p '{
-            "metadata": {
-              "labels": {"app.kubernetes.io/managed-by": "Helm"},
-              "annotations": {"meta.helm.sh/release-name": "flasksql-chart", "meta.helm.sh/release-namespace": "default"}
-            }
-          }' || echo "ConfigMap 'mysql-config' not found, skipping patch."
-
-      - name: Patch Existing Service 'gif-db' for Helm Adoption
-        run: |
-          echo "Patching Service 'gif-db' to include Helm ownership metadata"
-          kubectl patch service gif-db -n default --type merge -p '{
-            "metadata": {
-              "labels": {"app.kubernetes.io/managed-by": "Helm"},
-              "annotations": {"meta.helm.sh/release-name": "flasksql-chart", "meta.helm.sh/release-namespace": "default"}
-            }
-          }' || echo "Service 'gif-db' not found, skipping patch."
-
-      
-      - name: Deploy Helm Chart with CRDs
-        run: |
+          echo "🚀 Deploying Helm Chart to GKE"
           helm upgrade --install flasksql-chart ./charts/terraflaskqlk8s-chart \
             --namespace default \
+            -f charts/terraflaskqlk8s-chart/values.yaml \
             --set image.tag=$VERSION --version $VERSION
-            -f charts/terraflaskqlk8s-chart/values.yaml
-            
+
       - name: Verify Kubernetes Services
         run: |
           echo "Verifying Kubernetes Services"
@@ -266,11 +170,18 @@ jobs:
           helm repo add prometheus-community https://prometheus-community.github.io/helm-charts/
           helm repo update
 
-      - name: Verify Monitoring Is Up & Running
+      - name: Install Prometheus CRDs
         run: |
-          set -x
-          if kubectl get pods -n monitor | grep -qi grafana; then
-            echo "Monitor stack is up & running."
+          echo "Installing Prometheus CRDs for ServiceMonitor"
+          kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/servicemonitor.crd.yaml || echo "CRD already exists"
+
+      - name: Verify Monitoring Stack
+        run: |
+          echo "Checking if Prometheus and Grafana are running..."
+          kubectl get pods -n monitoring
+          if kubectl get pods -n monitoring | grep -qi grafana; then
+            echo "✅ Monitoring stack is up and running."
           else
+            echo "⚠️ Monitoring stack not found, deploying it now."
             helm upgrade --install my-monitoring prometheus-community/kube-prometheus-stack -n monitoring -f prometheus_values.yaml
           fi
